# Docker compose file for Development

services:
  # Back-end service
  gusmetal-back:
    build:
      context: ../../server
      dockerfile: docker/Dockerfile.dev
    ports:
      - "10000:8080"
    env_file:
      - ../../server/docker/.env
    volumes:
      - ../../server/src:/app/src
    container_name: gusmetal-back
    depends_on:
      gusmetal-db:
        condition: service_healthy
    links:
      - gusmetal-db:db

  # Front-end service
  gusmetal-front:
    build:
      context: ../../front
      dockerfile: docker/Dockerfile.dev
    ports:
      - "10001:3000"
    env_file:
      - ../../front/docker/.env.development
    volumes:
      - ../../front/app:/app/app
      - ../../front/public:/app/public
      # - ../../mobile/app/build/outputs/apk/debug/app-debug.apk:/app/public/gusmetal.apk
    container_name: gusmetal-front
    depends_on:
      - gusmetal-back

  # Database Service
  gusmetal-db:
    image: mariadb:10.11.3
    container_name: gusmetal-db
    env_file:
      - ../../database/.env
    volumes:
      - ../../database/db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  # Adminer
  gusmetal-adminer:
    image: adminer:4.8.1
    container_name: gusmetal-adminer
    ports:
      - "10002:8080"
    environment:
      # Designs listed at : https://github.com/vrana/adminer/tree/master/designs
      ADMINER_DESIGN: dracula
    depends_on:
      gusmetal-db:
        condition: service_healthy
    links:
      - gusmetal-db:db
