# Docker compose file for Development

services:
  # Back-end service
  acrousthetime-back:
    build:
      context: ../../server
      dockerfile: docker/Dockerfile.dev
    ports:
      - "10000:3000"
    env_file:
      - ../../server/docker/.env
    volumes:
      - ../../server/src:/app/src
    container_name: acrousthetime-back
    depends_on:
      acrousthetime-db:
        condition: service_healthy
    links:
      - acrousthetime-db:db

  # Front-end service
  acrousthetime-front:
    build:
      context: ../../front
      dockerfile: docker/Dockerfile.dev
    ports:
      - "10001:3000"
    env_file:
      - ../../front/docker/.env.development
    volumes:
      - ../../front/app:/app/app
      - ../../front/public:/app/public
      # - ../../mobile/app/build/outputs/apk/debug/app-debug.apk:/app/public/acrousthetime.apk
    container_name: acrousthetime-front
    depends_on:
      - acrousthetime-back

  # Database Service
  acrousthetime-db:
    image: postgres:15.4-alpine
    container_name: acrousthetime-db
    env_file:
      - ../../database/.env
    volumes:
      - ../../database/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 100

  # Adminer
  acrousthetime-adminer:
    image: adminer:4.8.1
    container_name: acrousthetime-adminer
    ports:
      - "10002:8080"
    environment:
      # Designs listed at : https://github.com/vrana/adminer/tree/master/designs
      ADMINER_DESIGN: dracula
    depends_on:
      acrousthetime-db:
        condition: service_healthy
    links:
      - acrousthetime-db:db
