# Dockerfile for deploying Next
FROM node:18.16.0

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Environment variables
ENV NEXT_PUBLIC_API_URL=https://api.acrousthetime.gugustinette.com

# Build the app
RUN npm run build

# Run the app
CMD [ "npm", "run", "start" ]
