# Docker compose file for Production

services:
  # Back-end service
  acrousthetime-back:
    build:
      context: ../../server
      dockerfile: docker/Dockerfile.prod
    ports:
      - "10000:8080"
    env_file:
      - ../../server/docker/.env
    container_name: acrousthetime-back
    depends_on:
      acrousthetime-db:
        condition: service_healthy
    links:
      - acrousthetime-db:db

  # Front-end service
  acrousthetime-front:
    build:
      context: ../../front
      dockerfile: docker/Dockerfile.prod
    ports:
      - "10001:3000"
    # env_file:
    #   - ../../front/docker/.env.production
    container_name: acrousthetime-front
    depends_on:
      - acrousthetime-back

  # Database Service
  acrousthetime-db:
    image: postgres:15.4-alpine
    container_name: acrousthetime-db
    env_file:
      - ../../database/.env
    volumes:
      - /var/acrousthetime/db:/var/lib/mysql
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 100
