# Dockerfile for Nest with Bun
FROM oven/bun:1.0

# Install procps so Nest can use the `ps` command
RUN apt-get update && apt-get install -y procps

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
COPY bun.lockb ./
RUN bun install

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Run the application
CMD [ "bun", "run", "start:dev" ]
